<a href="https://colab.research.google.com/github/RajiAbdulrahaman/AI_and_Drug_Discovery_Course_2026/blob/main/Assignment_2_QSAR_Data_Curation_Abdulrahman_Olamilekan_Raji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [30]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [31]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [32]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data’: Transport endpoint is not connected

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [33]:
!pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.2.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Requirement already satisfied: url-normalize>=1.4 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

# Step 1: Search for Traget Protein

## **Target Identification (RAD51)**
Search ChEMBL for the RAD51 target and select the most relevant entry.

In [34]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [35]:
target = new_client.target
target_query = target.search("RAD51")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Mus musculus,DNA repair protein RAD51 homolog 1,24.0,False,CHEMBL2034808,"[{'accession': 'Q08297', 'component_descriptio...",SINGLE PROTEIN,10090
1,[],Homo sapiens,DNA repair protein RAD51 homolog 1,23.0,False,CHEMBL2034807,"[{'accession': 'Q06609', 'component_descriptio...",SINGLE PROTEIN,9606

**Reterive Bioactivity data for selected target**

In [36]:
selected_target = targets.target_chembl_id[1]
selected_target

'CHEMBL2034807'

**Now retrieve only bioactivity data for target; **GTPase KRas(CHEMBL2189121)** with reported IC 50  values in nM (nanomolar) unit.**

In [37]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [38]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,3408163,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,2.1
1,None,None,3408164,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,3.5
2,None,None,3408165,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,3408166,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,11.0
4,None,None,3408167,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,40.0

In [39]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [40]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [41]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

cp: failed to access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected

In [42]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

ls: cannot access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected

In [43]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,3408163,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded DNA complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CNC(=O)[C@H](CC(C)C)NC(=O)[C@@H](N)CC(C)C)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '1.82', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215810,,CHEMBL1215810,5.68,0,http://www.openphacts.org/units/Nanomolar,933603,=,1,1,=,,IC50,nM,,2100.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,2.1
,,3408164,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded DNA complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '1.89', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215811,,CHEMBL1215811,5.46,0,http://www.openphacts.org/units/Nanomolar,933604,=,1,1,=,,IC50,nM,,3500.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,3.5
,,3408165,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded DNA complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@@H](N)Cc1cnc[nH]1)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,,CHEMBL1215812,,CHEMBL1215812,,0,http://www.openphacts.org/units/Nanomolar,933605,>,1,1,>,,IC50,nM,,100000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,100.0
,,3408166,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded DNA complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '1.87', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215813,,CHEMBL1215813,4.96,0,http://www.openphacts.org/units/Nanomolar,933606,=,1,1,=,,IC50,nM,,11000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,11.0
,,3408167,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded DNA complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@@H](N)Cc1ccccc1)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,,CHEMBL1215814,,CHEMBL1215814,,0,http://www.openphacts.org/units/Nanomolar,933607,>,1,1,>,,IC50,nM,,40000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,40.0
,,3408168,[],CHEMBL1219281,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded poly-(d-epsilonA) complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '1.87', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215813,,CHEMBL1215813,4.96,0,http://www.openphacts.org/units/Nanomolar,933606,=,1,1,=,,IC50,nM,,11000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,11.0
,,3408169,[],CHEMBL1219281,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded poly-(d-epsilonA) complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '1.93', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215815,,CHEMBL1215815,5.16,0,http://www.openphacts.org/units/Nanomolar,933608,=,1,1,=,,IC50,nM,,7000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,7.0
,,3408170,[],CHEMBL1219281,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded poly-(d-epsilonA) complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,,CHEMBL1215816,,CHEMBL1215816,,0,http://www.openphacts.org/units/Nanomolar,933609,>,1,1,>,,IC50,nM,,40000.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,40.0
,,3408171,[],CHEMBL1219281,Inhibition of human RAD51 assessed as dissociation of protein/single-stranded poly-(d-epsilonA) complex formation by fluorescence polarimetry,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H](NC(=O)[C@H](CCCCN)NC(=O)[C@H](CCCCN)NC(=O)CNC(=O)[C@H](CO)NC(=O)[C@H](C)NC(=O)[C@@H](NC(=O)[C@H](Cc1cnc[nH]1)NC(=O)[C@H](Cc1ccccc1)NC(=O)CN)[C@@H](C)O)C(C)C)C(=O)N[C@@H](CO)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CO)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCCCN)C(=O)N[C@H](C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(N)=O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)C(C)C,,,CHEMBL1212926,J Med Chem,2010,"{'bei': '2.10', 'le': None, 'lle': None, 'sei': None}",CHEMBL1215817,,CHEMBL1215817,5.60,0,http://www.openphacts.org/units/Nanomolar,933610,=,1,1,=,,IC50,nM,,2500.0,CHEMBL2034807,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,,,IC50,uM,UO_0000065,,2.5

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KRAS target.**

**Inspect Missing Values**

In [44]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [45]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,3408163,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,2.1
1,None,None,3408164,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,3.5
2,None,None,3408165,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,3408166,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,11.0
4,None,None,3408167,[],CHEMBL1219280,Inhibition of human RAD51 assessed as dissocia...,B,None,None,BAO_0000190,...,Homo sapiens,DNA repair protein RAD51 homolog 1,9606,None,None,IC50,uM,UO_0000065,None,40.0

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [46]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [47]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [48]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
     bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [49]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1215810,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,2100.0,intermediate
1,CHEMBL1215811,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,3500.0,intermediate
2,CHEMBL1215812,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,100000.0,inactive
3,CHEMBL1215813,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,11000.0,inactive
4,CHEMBL1215814,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,40000.0,inactive

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [50]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1215810,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,2100.0,intermediate
1,CHEMBL1215811,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,3500.0,intermediate
2,CHEMBL1215812,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,100000.0,inactive
3,CHEMBL1215813,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,11000.0,inactive
4,CHEMBL1215814,CC[C@H](C)[C@H](NC(=O)[C@H](CCCCN)NC(=O)[C@@H]...,40000.0,inactive

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [51]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

cp: failed to access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected
ls: cannot access '/content/gdrive/My Drive/Colab Notebooks/data': Transport endpoint is not connected

## **End of Part 1: Data Collection and Curation**